version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Web/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    networks:
      network:
        ipv4_address: 10.92.100.10

  # server2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8080"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.92.100.0/24